spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: "root"
    password: "183759"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  session:
#    session设置超时时间
    timeout: 600
#    session存储管理方式
    store-type: redis
server:
  port: 80
#自定义配置
sys:
  security:
    browser:
      signUpUrl: "/demo-signUp.html"
    social:
      filterProcessesUrl: "/login"
      qq:
        app-id: "101774723"
        app-secret: "512a28b1ab580bc1d31aaef87db28913"
      weinxin:
        app-id: "wxd99431bbff8305a0"
        app-secret: "60f78681d063590a469f1b297feff3c4"

